name: Cypress E2E Tests

on:
  pull_request:
    branches: ['develop']
  push:
    branches: ['main']

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Start Vite dev server
        run: npm run dev &
        env:
          CI: true

      - name: Wait for Vite server to start
        uses: jakejarvis/wait-action@master
        with:
          url: 'http://localhost:5173'
          timeout: '60'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npm run dev
          wait-on: 'http://localhost:5173'
